version: "3.9"

services:
  db:
    image: "postgres:latest"
    ports:
      - 2345:5432
    expose:
      - 5432
    env_file:
      - .env
  bot:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
    - .:/app